### ISSUE TITLE
Consider moving to GNU ELPA ?

### ISSUE THREAD

**Issue by phil-s** [clemera/objed#19]
This package (which sounds very nice) does not appear to depend upon any non-standard libraries or packages, so it doesn't look like it needs to be in MELPA?

Perhaps you would consider putting it into GNU ELPA instead?

GNU ELPA is available to users by default; it's easier for GNU ELPA packages to some day become part of Emacs; and GNU ELPA packages can be used as dependencies for other GNU ELPA packages, so other GNU ELPA package authors could potentially write add-ons for objed.

**Comment by clemera** [comment]
I like the idea that ELPA authors could use the package then, too. Could the package live on both archives (MELPA/ELPA)? The only objection I would have is that it's harder to contribute because the papers have to be signed for bigger contributions than 15 lines. But I guess this is bearable loss.

I would like to keep the project on github, could I mirror it from here to GNU ELPA? What are the steps necessary for me to go in that direction?

**Comment by clemera** [comment]
I thought about it and I think it is a bit to early to put it on ELPA. I will try to submit it there when the project is more stable. As soon as I commit to MELPA stable I will try to get it into ELPA, as well.

**Comment by clemera** [comment]
@phil-s Just wanted to let you know objed is on ELPA now!

**Comment by phil-s** [comment]
That's awesome news.  Thank you very much!
