### ISSUE TITLE
Object continuation: different commands for action > next object and action > previous object. 

### ISSUE THREAD

**Issue by yilkalargaw** [clemera/objed#62]
I want'd to rebind the objed-kill and both options of having the point move to previous object and having the point move to next object are both named objed-kill. It might be good when you bind the two commands to a single key but it makes it hard to remap them to different keys. So I think it might be better to have two separate commands like objed-kill-move-pt-next and  objed-kill-move-pt-previous (or something like that)

**Comment by clemera** [comment]
It would be possible to add distinct commands for that, but having `shift` to apply an action and move to previous opposed to apply and action and move to next is made on a more general level. So you would need a general rule how to bind such keys, or it would quickly get confusing. Do you have a general rule in mind? By that I mean how would you like to distinct `do action > move to next`, `do action > move to previous`?

**Comment by yilkalargaw** [comment]
I was trying to map the kill commands to "K" and "I" (i.e. shift-k and shift-i).

ps. By the way sorry for the repeated issues. It is because I had to do some adjustments to the way I type because of a recent accident.

**Comment by clemera** [comment]
Sorry to hear that, wish you a quick recovery! Currently `objed--get-continuation` determines the continuation object on exit . If shift was for the command then it gets the previous one otherwise the next. Using different commands would mean that we need to pass the info from the command down to `objed--get-continuation` somehow and also take care of distinguishing this from usual behavior.

**Comment by yilkalargaw** [comment]
Thanks. I was able to rebind it.
