### ISSUE TITLE
The reason behind the keybindings "h" and "l"

### ISSUE THREAD

**Issue by koleiskiy** [clemera/objed#71]
One of the best things in `objed` is that its keybindings are aligned with emacs conventions. 

However, keybindings `h` and `l` are from `vi` while `n` and `p` from emacs. I think this is confusing for some users who use `vi` or `vim`, and `emacs`. So I'd like to know the reason why you choose `h` and `l` for character-based movements.

Off course one can change the keybindings at will but the default should stick with emacs conventions, and using left and right arrow keys for character-based movements are better than using keybindings from `vi`, IMO. What do you think?

**Comment by clemera** [comment]
When I started `objed` the keybindings changed very often and more than one time I had to revert a decision because it conflicted with other use cases. I agree that `h` and `l` are not optimal, ideally one would use `f` and `b` but I came to the conclusion that those are more useful and intuitive for moving by s-expressions. I thought the alignment of `h` and `l` with `vi` might be little bonus but I can understand that they might be confusing if you are using both. The arrow keys are ok but I think char based movement should be possible without reaching for them.

**Comment by koleiskiy** [comment]
I too think using `f` and `b` as s-expression movements is really useful. 

I have one more concern about `h` and `l`: They are heavily based on `qwerty` keyboard layout. 

It would be nice if `objed` could have keyboard layout unaware keybindings so some users who use keyboard layouts other than `qwerty` can use `objed` right away.

If you are willing to change keybindings, how about `c` to `objed-left-char` (from [c]haracter) and `h` to `objed-right-char` (from c[h]haracter)? But then, `objed-object-map` has to be assigned other key...

**Comment by clemera** [comment]
`c` and `x` derive from Emacs default prefix keys `C-c` and `C-x` so I wouldn't like to change the binding for `c`. In general I'm not opposed to find a better binding for char movement but it will be hard to find one that justfies a change I guess.

**Comment by koleiskiy** [comment]
I think there are no better keybindings for character movements because the current other keybindings are almost perfect. Also `h` and `l` can be seen as `high` and `low` in term of column number.

Thank you for answering my questions and your work on `objed` :)

**Comment by clemera** [comment]
You are welcome!
