### ISSUE TITLE
objed-extend face not being applied correctly when expanding a region?

### ISSUE THREAD

**Issue by moesasji** [clemera/objed#81]
In an attempt to get objed integrated into [modus-themes, see bug](https://gitlab.com/protesilaos/modus-themes/-/issues/79) I noticed that the face on an extend isn't applied in the way I expected. The screenshot below shows this problem.  

![objed-extend-face](https://user-images.githubusercontent.com/1714738/91631677-50220700-e9d3-11ea-963c-349806825398.png)

The first region is a marked region, the second a region that is being expanded using `@`. The syntax not being visible in that second region indicates that the `region` face is being applied instead of the one corresponding to the `objed-extend` face I was expecting based on its definition.

btw) it would be great if you could take a look whether the colors added to modus-theme fit with your vision for objed as I'm not sure what is optimal for extending as it looking as marked feels counter intuitive to me, see above link.

**Comment by clemera** [comment]
Thanks you are right, it's indeed the region face that gets applied there because internally this command uses the active region. Looking at this now I think `objed-extend` wouldn't need to be an extra face because it should look the same as usual selection (using the region face). It is meant as a command which "converts" the active object to a malleable region you can adjust via objeds movement commands.

I think we can leave the face there but let it inherit it from `region` by default and also fix the face remapping by `objed-extend` so that the `objed-expand` face is actually used for the whole selection, so you could still use a different face for that if you like. WDYT?

**Comment by moesasji** [comment]
Thanks for taking such a quick look. 

Personally I'm not a fan of the bare region face as it looses all syntax high-lighting in most color-themes. My preferred solution would be if the face used when extending would use the same face as when selecting using objed-hl. Essentially the same appearance as below in which the top region is marked, the second region a selected function-block. At the moment "extending" looks like the screenshot in the start-post, which I find counter intuitive and the difference has no real purpose as far as I can tell.

![marked-vs-selected](https://user-images.githubusercontent.com/1714738/91633429-1b687c80-e9e0-11ea-9e4b-9983746c78df.png)

**Comment by protesilaos** [comment]
Thanks for looking into this! Just to note that I am monitoring this and am prepared to implement any changes for the themes.

**Comment by clemera** [comment]
The reason why I think it should show the region face is because that is what the command actually does: It instantiates a region containing the current object and then you can extend that region using movement commands. This is similar to activating the region using `C-SPC` with the difference that your region doesn't start empty. If you would use `objed-hl` face you wouldn't be able to see the difference visually whereas the region face tells you it is a region and it behaves like one.

That said when I change it like I described you can still set the face to inherit from `objed-hl` if you like.

@protesilaos Nice to see your themes have been added to Emacs, congrats and thanks for working on this, I will try them soon!

**Comment by clemera** [comment]
While looking at this I also noticed that marking objects and then start to extending one isn't a case that is properly supported. I will have to open another issue for that.

**Comment by clemera** [comment]
Given that the `objed-extend` wasn't correctly applied and I don't think it makes sense to have it at all I removed it. Thanks @moesasji to make me aware of it. As I mentioned above the command is only  meant as a helper to instantiate a region containing the current object. When the region is active it will be used by objed operations as the current object boundaries.

**Comment by clemera** [comment]
I will close this since the face got removed but if there are any more problems adding objed support to the themes I'm happy to help of course.

**Comment by protesilaos** [comment]
Thanks!  Yesterday I also removed that face from the themes.  All good!
