### ISSUE TITLE
Avoid dropping out of objed-mode when using isearch

### ISSUE THREAD

**Issue by moesasji** [clemera/objed#88]
> If I understand correctly you would like to automatically reenter objed after an isearch (when objed was active on search start)? That could be added, if you like open another issue for that.

As mentioned in #78 I find the fact that I am dropped out of objed-mode when using isearch surprising and don't immediately see the benefit of that happening. Would it be possible to add the ability to automatically re-enter objed-mode on exiting isearch?.

**Comment by clemera** [comment]
This is because any non objed command usually automatically exits objed. Commands which should not exit objed should be added to `objed-keeper-commands`. This won't work for isearch out of the box because it needs some special handling but I think it makes sense to add the isearch commands to the keeper commands by default. 

As you said in another comment you would like to use objed as the default state in this case you probably never want to exit objed automatically? I will have to think about what else would need to be adjusted for this use case.

**Comment by clemera** [comment]
Isearch is now added to `objed-keeper-commands` and handled accordingly. Could you test and close if it works as expected?

**Comment by moesasji** [comment]
Seems to work for my basic usage although two commands are missing:
```
isearch-forward-symbol-at-point
isearch-forward-word
```
in reality you have a better binding for the functionality the first one offers anyway, but adding these for consistency might be worth it.

**Comment by clemera** [comment]
Thanks, I added them.

**Comment by moesasji** [comment]
works for me.
